const SPREADSHEET_ID="1vEjY1z-147b38XTWV7vRm_9pjXVMfJmjdQtrKRkkLy8";
const S={U:"USER_MASTER",O:"OFFICE_MASTER",R:"PMV_REPORTS",S:"SESSIONS",A:"AUDIT_LOG"},ROLES={SPM:"SPM",DPS:"DPS",ADMIN:"ADMIN"},TZ="Asia/Kolkata";
function setupSpreadsheet(){let ss=SpreadsheetApp.openById(SPREADSHEET_ID),d={USER_MASTER:["USER_ID","NAME","MOBILE","ROLE","OFFICE_ID","OFFICE_NAME","ACTIVE"],OFFICE_MASTER:["OFFICE_ID","OFFICE_NAME","DIVISION","ACTIVE"],PMV_REPORTS:["ID","DATE","OFFICE_ID","OFFICE_NAME","SPM_ID","SPM_NAME","OPENING_KITS","NEW_KITS","REDIRECTED_KITS","RTS_KITS","DELIVERED_KITS","INVALID_MOBILE_KITS","TORN_KITS","DELIVERABLE_KITS","INCOMPLETE_KITS","CLOSING_PENDING_KITS","OPENING_ARTICLES","NEW_ARTICLES","REDIRECTED_ARTICLES","RTS_ARTICLES","DELIVERED_ARTICLES","INVALID_MOBILE_ARTICLES","TORN_ARTICLES","DELIVERABLE_ARTICLES","INCOMPLETE_ARTICLES","CLOSING_PENDING_ARTICLES","SUBMITTED_AT","UPDATED_AT","STATUS"],SESSIONS:["TOKEN","USER_ID","CREATED_AT","EXPIRES_AT","ACTIVE"],AUDIT_LOG:["TIMESTAMP","USER_ID","ACTION","DETAILS"]};Object.keys(d).forEach(n=>{let sh=ss.getSheetByName(n)||ss.insertSheet(n);if(sh.getLastRow()==0)sh.appendRow(d[n]);sh.setFrozenRows(1)});return"Setup complete";}
function doGet(e){try{let p=e.parameter||{},s=need(p.session);if(p.action=="getAdminPmvDashboard")return out(admin(p.date,s));if(p.action=="getPmvOpeningBalance")return out(opening(p.date,s));if(p.action=="getOwnPmvDashboard")return out(own(p.date,s));return out(err("Unknown GET action."))}catch(x){return out(err(x.message))}}
function doPost(e){try{let b=JSON.parse(e.postData.contents||"{}");if(b.action=="login")return out(login(b.userId,b.mobile));if(b.action=="logout")return out(logout(b.session));if(b.action=="submitPmvReport")return out(submit(b.record,b.session));return out(err("Unknown POST action."))}catch(x){return out(err(x.message))}}
function login(id,m){let u=findUser(id);if(!u)return err("User not found.");if(String(u.MOBILE).trim()!=String(m).trim())return err("Mobile number does not match our records.");if(!act(u.ACTIVE))return err("This account is inactive.");let role=String(u.ROLE).toUpperCase(),t=Utilities.getUuid(),n=new Date(),x=new Date(n.getTime()+7*86400000);sheet(S.S).appendRow([t,u.USER_ID,n,x,true]);return ok({userId:String(u.USER_ID),name:String(u.NAME||""),role,officeId:String(u.OFFICE_ID||""),officeName:String(u.OFFICE_NAME||""),token:t,expiresAt:x.toISOString()})}
function logout(s){auth(s);let v=rows(S.S);v.forEach((r,i)=>{if(String(r.TOKEN)==String(s.token))sheet(S.S).getRange(r.__row,5).setValue(false)});return ok(null,"Logged out.")}
function submit(z,s){let a=auth(s);if(a.role!="SPM")throw Error("Only SPM users can submit.");z=z||{};let r=norm(z),o=office(a.user.OFFICE_ID);r.officeId=String(a.user.OFFICE_ID);r.officeName=o.OFFICE_NAME;r.spmId=a.user.USER_ID;r.spmName=a.user.NAME;r.openingKits=prev(r.officeId,r.date,"K");r.openingArticles=prev(r.officeId,r.date,"A");r.closingPendingKits=r.openingKits+r.newKits-r.redirectedKits-r.rtsKits-r.deliveredKits;r.closingPendingArticles=r.openingArticles+r.newArticles-r.redirectedArticles-r.rtsArticles-r.deliveredArticles;let ek=r.invalidMobileKits+r.tornKits+r.deliverableKits+r.incompleteKits,ea=r.invalidMobileArticles+r.tornArticles+r.deliverableArticles+r.incompleteArticles;if(r.closingPendingKits<0||r.closingPendingArticles<0)throw Error("Movement exceeds available stock.");if(r.closingPendingKits!=ek)throw Error("Kit validation failed: closing pending must equal invalid mobile + torn/without address + deliverable + incomplete.");if(r.closingPendingArticles!=ea)throw Error("Article validation failed: closing pending must equal invalid mobile + torn/without address + deliverable + incomplete.");let old=findReport(r.spmId,r.date),row=[r.id,r.date,r.officeId,r.officeName,r.spmId,r.spmName,r.openingKits,r.newKits,r.redirectedKits,r.rtsKits,r.deliveredKits,r.invalidMobileKits,r.tornKits,r.deliverableKits,r.incompleteKits,r.closingPendingKits,r.openingArticles,r.newArticles,r.redirectedArticles,r.rtsArticles,r.deliveredArticles,r.invalidMobileArticles,r.tornArticles,r.deliverableArticles,r.incompleteArticles,r.closingPendingArticles,new Date(),new Date(),"FINAL"];if(old)sheet(S.R).getRange(old.__row,1,1,row.length).setValues([row]);else sheet(S.R).appendRow(row);return ok({recordId:r.id,closingPendingKits:r.closingPendingKits,closingPendingArticles:r.closingPendingArticles},"Report saved successfully.")}
function admin(date,s){let a=auth(s);if(a.role!="ADMIN"&&a.role!="DPS")throw Error("Only DPS/Admin users can access this function.");date=String(date||today());let us=rows(S.U).filter(x=>act(x.ACTIVE)&&String(x.ROLE).toUpperCase()=="SPM"),rs=rows(S.R).filter(x=>dateOf(x.DATE)==date),bm={};rs.forEach(r=>bm[String(r.SPM_ID)]=r);let om={};rows(S.O).filter(x=>act(x.ACTIVE)).forEach(o=>om[String(o.OFFICE_ID)]=baseOffice(o));let pending=[];us.forEach(u=>{let id=String(u.USER_ID),o=om[String(u.OFFICE_ID)]||(om[String(u.OFFICE_ID)]=baseOffice(u));o.totalSpms++;if(bm[id])o.updatedSpms++;else{o.pendingSpms++;pending.push({spmName:u.NAME,spmId:id,officeName:o.officeName})}});let sum={newKits:0,newArticles:0,redirectedKits:0,redirectedArticles:0,rtsKits:0,rtsArticles:0,deliveredKitsToday:0,deliveredArticlesToday:0,closingPendingKits:0,closingPendingArticles:0,invalidMobileKits:0,incompleteKits:0};rs.forEach(r=>{["newKits","newArticles","redirectedKits","redirectedArticles","rtsKits","rtsArticles","deliveredKitsToday","deliveredArticlesToday","closingPendingKits","closingPendingArticles","invalidMobileKits","incompleteKits"].forEach(k=>{let col=k=="deliveredKitsToday"?"DELIVERED_KITS":k=="deliveredArticlesToday"?"DELIVERED_ARTICLES":k.replace(/[A-Z]/g,m=>"_"+m).toUpperCase();sum[k]+=num(r[col])});let o=om[String(r.OFFICE_ID)]||(om[String(r.OFFICE_ID)]=baseOffice(r));o.openingKits+=num(r.OPENING_KITS);o.newKits+=num(r.NEW_KITS);o.redirectedKits+=num(r.REDIRECTED_KITS);o.rtsKits+=num(r.RTS_KITS);o.deliveredKits+=num(r.DELIVERED_KITS);o.closingPendingKits+=num(r.CLOSING_PENDING_KITS);o.openingArticles+=num(r.OPENING_ARTICLES);o.newArticles+=num(r.NEW_ARTICLES);o.redirectedArticles+=num(r.REDIRECTED_ARTICLES);o.rtsArticles+=num(r.RTS_ARTICLES);o.deliveredArticles+=num(r.DELIVERED_ARTICLES);o.closingPendingArticles+=num(r.CLOSING_PENDING_ARTICLES)});return ok({date,summary:sum,officeWise:Object.values(om).map(o=>({...o,status:o.totalSpms&&o.updatedSpms==o.totalSpms?"Updated":"Pending"})),pendingSpms:pending,spmsUpdatedToday:rs.length,activeSpms:us.length,spmsPendingUpdate:pending.length})}
function opening(date,s){let a=auth(s),r=prev(String(a.user.OFFICE_ID),String(date||today()),"R");return ok({openingKits:r.openingKits||0,openingArticles:r.openingArticles||0})}
function own(date,s){let a=auth(s),r=findReport(a.user.USER_ID,String(date||today()));return ok(r||null)}
function prev(oid,d,t){let q=rows(S.R).filter(r=>String(r.OFFICE_ID)==String(oid)&&dateOf(r.DATE)<d).sort((a,b)=>dateOf(b.DATE).localeCompare(dateOf(a.DATE)));if(!q.length)return 0;return t=="K"?num(q[0].CLOSING_PENDING_KITS):t=="A"?num(q[0].CLOSING_PENDING_ARTICLES):q[0]}
function norm(x){let r={};Object.keys(x).forEach(k=>r[k]=x[k]);["newKits","newArticles","redirectedKits","redirectedArticles","rtsKits","rtsArticles","deliveredKits","deliveredArticles","invalidMobileKits","invalidMobileArticles","tornKits","tornArticles","deliverableKits","deliverableArticles","incompleteKits","incompleteArticles"].forEach(k=>r[k]=Math.max(0,Math.floor(num(r[k]))));r.id=r.id||Utilities.getUuid();r.date=String(r.date||today());return r}
function baseOffice(x){return{officeId:String(x.OFFICE_ID||""),officeName:String(x.OFFICE_NAME||""),totalSpms:0,updatedSpms:0,pendingSpms:0,openingKits:0,newKits:0,redirectedKits:0,rtsKits:0,deliveredKits:0,closingPendingKits:0,openingArticles:0,newArticles:0,redirectedArticles:0,rtsArticles:0,deliveredArticles:0,closingPendingArticles:0}}
function findReport(id,d){return rows(S.R).find(r=>String(r.SPM_ID)==String(id)&&dateOf(r.DATE)==d)}
function findUser(id){return rows(S.U).find(r=>String(r.USER_ID).trim()==String(id).trim())}
function office(id){let o=rows(S.O).find(r=>String(r.OFFICE_ID)==String(id));if(!o)throw Error("Office not found.");return o}
function auth(s){if(!s||!s.userId||!s.token)throw Error("Not authenticated.");let r=rows(S.S).find(x=>String(x.TOKEN)==String(s.token)&&String(x.USER_ID)==String(s.userId)&&act(x.ACTIVE));if(!r)throw Error("Session expired or invalid.");if(new Date(r.EXPIRES_AT)<=new Date()){throw Error("Session expired. Please log in again.")}let u=findUser(s.userId);if(!u||!act(u.ACTIVE))throw Error("Account is inactive.");return{user:u,role:String(u.ROLE).toUpperCase()}}
function need(x){if(!x)throw Error("Not authenticated.");return JSON.parse(x)}
function rows(n){let sh=sheet(n),v=sh.getDataRange().getValues(),h=v.shift()||[];return v.map((r,i)=>{let o={__row:i+2};h.forEach((k,j)=>o[k]=r[j]);return o})}
function sheet(n){let s=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(n);if(!s)throw Error("Missing sheet "+n+". Run setupSpreadsheet().");return s}
function dateOf(v){return v instanceof Date?Utilities.formatDate(v,TZ,"yyyy-MM-dd"):String(v||"").slice(0,10)}
function today(){return Utilities.formatDate(new Date(),TZ,"yyyy-MM-dd")}
function num(v){let n=Number(v);return isFinite(n)?n:0}
function act(v){return v===true||["true","yes","1","active","y"].indexOf(String(v).toLowerCase().trim())>=0}
function ok(data,message){return{success:true,data:data===undefined?null:data,message:message||"OK"}}
function err(message){return{success:false,message}}
function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}